/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IContentHashResolverInterface extends utils.Interface {
  functions: {
    "contenthash(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "contenthash",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "contenthash",
    data: BytesLike
  ): Result;

  events: {
    "ContenthashChanged(bytes32,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContenthashChanged"): EventFragment;
}

export type ContenthashChangedEvent = TypedEvent<
  [string, string],
  { node: string; hash: string }
>;

export type ContenthashChangedEventFilter =
  TypedEventFilter<ContenthashChangedEvent>;

export interface IContentHashResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IContentHashResolverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    contenthash(node: BytesLike, overrides?: CallOverrides): Promise<[string]>;
  };

  contenthash(node: BytesLike, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    contenthash(node: BytesLike, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ContenthashChanged(bytes32,bytes)"(
      node?: BytesLike | null,
      hash?: null
    ): ContenthashChangedEventFilter;
    ContenthashChanged(
      node?: BytesLike | null,
      hash?: null
    ): ContenthashChangedEventFilter;
  };

  estimateGas: {
    contenthash(node: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    contenthash(
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
