/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface INameWrapperUpgradeInterface extends utils.Interface {
  functions: {
    "wrapFromUpgrade(bytes,address,uint32,uint64,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "wrapFromUpgrade",
    values: [BytesLike, string, BigNumberish, BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "wrapFromUpgrade",
    data: BytesLike
  ): Result;

  events: {};
}

export interface INameWrapperUpgrade extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: INameWrapperUpgradeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    wrapFromUpgrade(
      name: BytesLike,
      wrappedOwner: string,
      fuses: BigNumberish,
      expiry: BigNumberish,
      approved: string,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  wrapFromUpgrade(
    name: BytesLike,
    wrappedOwner: string,
    fuses: BigNumberish,
    expiry: BigNumberish,
    approved: string,
    extraData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    wrapFromUpgrade(
      name: BytesLike,
      wrappedOwner: string,
      fuses: BigNumberish,
      expiry: BigNumberish,
      approved: string,
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    wrapFromUpgrade(
      name: BytesLike,
      wrappedOwner: string,
      fuses: BigNumberish,
      expiry: BigNumberish,
      approved: string,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    wrapFromUpgrade(
      name: BytesLike,
      wrappedOwner: string,
      fuses: BigNumberish,
      expiry: BigNumberish,
      approved: string,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
